// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUyZ1Nmq1DLyku0l27GqrIzHpvQT4yld4',
    appId: '1:248040794875:web:cdff68145c2f183f3b9e5e',
    messagingSenderId: '248040794875',
    projectId: 'collection-tracker-database',
    authDomain: 'collection-tracker-database.firebaseapp.com',
    storageBucket: 'collection-tracker-database.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDak7UrXArqRJqil18ooOnTo3z-ykH8ZcU',
    appId: '1:248040794875:android:81a46a31271d70e33b9e5e',
    messagingSenderId: '248040794875',
    projectId: 'collection-tracker-database',
    storageBucket: 'collection-tracker-database.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2NAIrsqaIppkhDmG-g8uMrTeV8myhEDQ',
    appId: '1:248040794875:ios:5980910120358e583b9e5e',
    messagingSenderId: '248040794875',
    projectId: 'collection-tracker-database',
    storageBucket: 'collection-tracker-database.firebasestorage.app',
    iosBundleId: 'com.example.collectionTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2NAIrsqaIppkhDmG-g8uMrTeV8myhEDQ',
    appId: '1:248040794875:ios:5980910120358e583b9e5e',
    messagingSenderId: '248040794875',
    projectId: 'collection-tracker-database',
    storageBucket: 'collection-tracker-database.firebasestorage.app',
    iosBundleId: 'com.example.collectionTracker',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUyZ1Nmq1DLyku0l27GqrIzHpvQT4yld4',
    appId: '1:248040794875:web:2b47dd565e8da4d83b9e5e',
    messagingSenderId: '248040794875',
    projectId: 'collection-tracker-database',
    authDomain: 'collection-tracker-database.firebaseapp.com',
    storageBucket: 'collection-tracker-database.firebasestorage.app',
  );
}
